name: Bem-vindo ao Github Actions meu caro.

on: push

jobs:
  ola-amigo:
    runs-on: ubuntu-latest
    steps:
      -name: comprimento
      run: echo "💡 Ola meu caro, bem vindo ao github actions!."
    